---
title: "dada 2 analyse"
output: github_document
---



```{r}
library(dada2)
library(vegan)
```






```{r}
path <- "/home/rstudio/dada2/dada2/MiSeq_SOP"

list.files(path)


# Forward and reverse fastq filenames have format: SAMPLENAME_R1_001.fastq and SAMPLENAME_R2_001.fastq

fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))

# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq

sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)


```

```{r}
plotQualityProfile(fnFs[1:2]) #reads
plotQualityProfile(fnRs[1:2]) #reverse reads

# Correspond à profondeur d'échantillonage
# fastq associe à chaque nucleotique un score de qualité -> qscore indiqué par des caractères (estimation de la proba d'avoir une erreur dans l'assignation de la base) = 30 ->  (1 / 1000) par exemple
# qscore = 20 -> une chance sur 100, qscore = 40 -> une chance sur 10 000
# ligne verte : q score, moyenne des scores de qualité pour les séquences à chaque position 


# bcp moins bonne qualité pour les reverses (souvent le cas)
# On ne veut pas utiliser les régions avec faible score de qualité : on garde les partie de R1 et R2 avec bon score, mais longueur doit rester suffisante pour pas perdre information. si longueur total = 400nu, R1 = 200 et R2 = 200 passe mais pas trop supprimer (à modifier selon les séquences utilisées). -> on doit avoir accès à longueur de V3 ici
```
```{r}
# Place filtered files in filtered/ subdirectory
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names




out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),  #240 nu pour forward et 160 pour reverse (moins bonne qualité sur reverse)
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=FALSE) # On Windows set multithread=FALSE (only needed for filterAndTrim)
head(out)
# On utilise l'ADN de phix pour vérifier le run de sequençage


```
```{r}
errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)
# vecteurs contiennent les modèles d'erreurs identifiés par dada2

plotErrors(errF, nominalQ=TRUE)

```
```{r}
#On applique l'algorythme à notre data filtré et trimmed + en corrigeant les erreurs (on utilise reads filtré et objects erreurs)

dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
#sample global parameters
dadaFs[[1]]
#128 sequence variants were inferred from 1979 input unique sequences.
#Key parameters: OMEGA_A = 1e-40, OMEGA_C = 1e-40, BAND_SIZE = 16
#Object r dépend de la fonction

```

```{r}

mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
# Inspect the merger data.frame from the first sample, superposition des reads. On supprime les séquences qui n'ont pas overlap parfaitement
# List of dataframe from each samples
head(mergers[[1]])

```

```{r}
#Construct sequence table
seqtab <- makeSequenceTable(mergers)
dim(seqtab)

#la distribution de la taille des séquences
table(nchar(getSequences(seqtab)))
# Les séquences très longues ou très courtes peuvent être signe d'un couplage non spécifique

```

```{r}
#amplicon sequence variant table (ASV)
#Remove chimera script : si complexe ADN pol et brin matrice + nouveau brin est déformé, la polymérisation s'arrète avant la fin, le brin d'ADN n'est pas complet. au cycle suivant -> s'hybride à un autre 16S d'une autre bactérie, formation d'une chimère. Une moitié vient d'un 16s et l'autre d'un autre 16s. Erreur commune.


seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)

sum(seqtab.nochim)/sum(seqtab)
#On a gardé ~96% des observations, pas 96% des séquences


```

```{r}
# On regarde le nombre de reads qui ont passés chaque étapes du process. 


getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
# If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)

# exemple : merge enlève trop de séquences : trop de truncage

```
```{r}
taxa <- assignTaxonomy(seqtab.nochim,  "/home/rstudio/dada2/dada2/silva_nr99_v138.1_train_set.fa.gz", multithread=TRUE)

taxa <- addSpecies(taxa, "/home/rstudio/dada2/dada2/silva_species_assignment_v138.1.fa.gz")

taxa.print <- taxa # Removing sequence rownames for display only
rownames(taxa.print) <- NULL
head(taxa.print)
# largemenent dominé par Bacteroidota (fecal samples)
```

```{r}
# Accuracy evaluation : mock community -> 20 known sequences. On calcule la précision de dada2 sur des séquences connues. Cette évaluation s'applique uniquement à ce jeu de données


unqs.mock <- seqtab.nochim["Mock",]
unqs.mock <- sort(unqs.mock[unqs.mock>0], decreasing=TRUE) # Drop ASVs absent in the Mock
cat("DADA2 inferred", length(unqs.mock), "sample sequences present in the Mock community.\n")


mock.ref <- getSequences(file.path(path, "HMP_MOCK.v35.fasta"))
match.ref <- sum(sapply(names(unqs.mock), function(x) any(grepl(x, mock.ref))))
cat("Of those,", sum(match.ref), "were exact matches to the expected reference sequences.\n")

# Ici on à 20 séquences detectée, et 20 séquences correspondant aux séquences de référence : dada2 n'a pas fait d'erreur dans le tri des séquences. Bravo dada2
```


```{r}



```




```{r}
#représentation graphique

library(phyloseq); packageVersion("phyloseq")

library(Biostrings); packageVersion("Biostrings")
library(ggplot2); packageVersion("ggplot2")


```

```{r}
theme_set(theme_bw())

samples.out <- rownames(seqtab.nochim)
subject <- sapply(strsplit(samples.out, "D"), `[`, 1)
gender <- substr(subject,1,1)
subject <- substr(subject,2,999)
day <- as.integer(sapply(strsplit(samples.out, "D"), `[`, 2))
samdf <- data.frame(Subject=subject, Gender=gender, Day=day)
samdf$When <- "Early"
samdf$When[samdf$Day>100] <- "Late"
rownames(samdf) <- samples.out


ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE),
               sample_data(samdf),
               tax_table(taxa))
ps <- prune_samples(sample_names(ps) != "Mock", ps) # Remove mock sample


```

